FROM maven:3.6.3-openjdk-11 AS build
WORKDIR /usr/src/app/
COPY /26_webservices/src  /usr/src/app/src
COPY /26_webservices/pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean compile package -DskipTests

FROM tomcat:9.0.48-jdk11-openjdk
RUN rm -rf /usr/local/tomcat/webapps/*
COPY --from=build /usr/src/app/target/ROOT.war /usr/local/tomcat/webapps/
EXPOSE 8080
CMD ["catalina.sh", "run"]