FROM node:16.17.1-alpine
ENV PATH /usr/src/app/angular/node_modules/.bin:$PATH
WORKDIR /usr/src/app/angular
COPY /angular/package.json /usr/src/app/angular/package.json
RUN npm install -g @angular/cli@13.2.6
COPY /angular /usr/src/app/angular
EXPOSE 4200
#CMD ng serve --host 0.0.0.0 --port 4200